/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dao.ConnectionProvider;
import com.mysql.cj.xdevapi.Statement;
import java.awt.Color;
import java.time.DayOfWeek;
import java.util.List;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import utility.BDUtility;
import java.sql.*;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Connection;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.FileOutputStream;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Aditya Pandit
 */
public class ViewAttendance extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewAttendance.class.getName());

    /**
     * Creates new form ViewAttendance
     */
    public ViewAttendance() {
        initComponents();
        BDUtility.setImage(this, "images/abc2.jpg", 1101, 501);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.WHITE));

        dateChooserFrom.setDateFormatString("yyyy-MM-dd");
        dateChooserTo.setDateFormatString("yyyy-MM-dd");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        dateChooserTo = new com.toedter.calendar.JDateChooser();
        dateChooserFrom = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnResetFilters = new javax.swing.JButton();
        btnGenerateReport = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        presentLBL = new javax.swing.JLabel();
        lblPresent = new javax.swing.JLabel();
        absentLBL = new javax.swing.JLabel();
        lblAbsent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Attendance Track");

        btnExit.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnExit.setText("X");
        btnExit.addActionListener(this::btnExitActionPerformed);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userTable);

        dateChooserTo.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        dateChooserTo.addPropertyChangeListener(this::dateChooserToPropertyChange);

        dateChooserFrom.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        dateChooserFrom.addPropertyChangeListener(this::dateChooserFromPropertyChange);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("On / From");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To");

        btnResetFilters.setBackground(new java.awt.Color(153, 153, 153));
        btnResetFilters.setForeground(new java.awt.Color(0, 0, 0));
        btnResetFilters.setText("Reset Filters");
        btnResetFilters.addActionListener(this::btnResetFiltersActionPerformed);

        btnGenerateReport.setBackground(new java.awt.Color(153, 153, 153));
        btnGenerateReport.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerateReport.setText("Get Report");
        btnGenerateReport.addActionListener(this::btnGenerateReportActionPerformed);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        presentLBL.setBackground(new java.awt.Color(255, 255, 255));
        presentLBL.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        presentLBL.setForeground(new java.awt.Color(255, 255, 255));
        presentLBL.setText("Present :");

        lblPresent.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblPresent.setForeground(new java.awt.Color(0, 255, 102));
        lblPresent.setText("---------");

        absentLBL.setBackground(new java.awt.Color(255, 255, 255));
        absentLBL.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        absentLBL.setForeground(new java.awt.Color(255, 255, 255));
        absentLBL.setText("Absent :");

        lblAbsent.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblAbsent.setForeground(new java.awt.Color(255, 0, 51));
        lblAbsent.setText("---------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(presentLBL)
                    .addComponent(absentLBL))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAbsent)
                    .addComponent(lblPresent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presentLBL)
                    .addComponent(lblPresent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(absentLBL)
                    .addComponent(lblAbsent))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(393, 393, 393)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnResetFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(236, 236, 236))
                                    .addComponent(txtSearch))))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFiltersActionPerformed

        dateChooserFrom.setDate(null);
        dateChooserTo.setDate(null);
        txtSearch.setText("");

        loadDataInTable();

    }//GEN-LAST:event_btnResetFiltersActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        loadDataInTable();
    }//GEN-LAST:event_formComponentShown

    private void dateChooserFromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserFromPropertyChange
        loadDataInTable();
    }//GEN-LAST:event_dateChooserFromPropertyChange

    private void dateChooserToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserToPropertyChange
        loadDataInTable();
    }//GEN-LAST:event_dateChooserToPropertyChange

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        try {

            loadDataInTable();

            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("C:\\Users\\Aditya Pandit\\Downloads\\AttendanceReport.pdf"));
            document.open();

            document.add(new Paragraph("STUDENT ATTENDANCE REPORT\n\n"));

            String fromDate = (dateChooserFrom.getDate() != null) ? dateChooserFrom.getDate().toString() : "N/A";
            String toDate = (dateChooserTo.getDate() != null) ? dateChooserTo.getDate().toString() : "N/A";

            document.add(new Paragraph("From Date: " + fromDate));
            document.add(new Paragraph("To Date: " + toDate + "\n\n"));

            PdfPTable pdfTable = new PdfPTable(userTable.getColumnCount());

            // Column headers
            for (int i = 0; i < userTable.getColumnCount(); i++) {
                pdfTable.addCell(userTable.getColumnName(i));
            }

            for (int rows = 0; rows < userTable.getRowCount(); rows++) {
                for (int cols = 0; cols < userTable.getColumnCount(); cols++) {
                    Object value = userTable.getValueAt(rows, cols);
                    pdfTable.addCell(value == null ? "" : value.toString());
                }
            }

            document.add(pdfTable);

            if (lblPresent.isVisible() && lblAbsent.isVisible()) {
                document.add(new Paragraph("\n"));
                document.add(new Paragraph("Total Present: " + lblPresent.getText()));
                document.add(new Paragraph("Total Absent: " + lblAbsent.getText()));
            }

            document.close();

            JOptionPane.showMessageDialog(null, "Report Generated Successfully!");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }

    }//GEN-LAST:event_btnGenerateReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewAttendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel absentLBL;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnResetFilters;
    private com.toedter.calendar.JDateChooser dateChooserFrom;
    private com.toedter.calendar.JDateChooser dateChooserTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAbsent;
    private javax.swing.JLabel lblPresent;
    private javax.swing.JLabel presentLBL;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables

    private void loadDataInTable() {

        List<String> columns = new ArrayList<>(Arrays.asList(
                "ID", "Name", "Gender", "Email", "Date", "CheckIn", "CheckOut", "Status"
        ));

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns.toArray());
        userTable.setModel(model);

        try {

            String searchText = txtSearch.getText().trim();

            Date fromDateCal = dateChooserFrom.getDate();
            Date toDateCal = dateChooserTo.getDate();

            LocalDate fromDate = null;
            LocalDate toDate = null;

            if (fromDateCal != null) {
                fromDate = fromDateCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            }
            if (toDateCal != null) {
                toDate = toDateCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            }

            Connection con = ConnectionProvider.getCon();
            java.sql.Statement st = con.createStatement();

            // 🔥 SEARCH VALIDATION
            Integer searchId = null;
            if (!searchText.isEmpty()) {
                try {
                    searchId = Integer.parseInt(searchText);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Enter valid numeric ID");
                    return;
                }
            }

            // 🔥 SPECIAL CASE: ID + DATE RANGE
            if (searchId != null && fromDate != null && toDate != null) {

                String sqlQuery = "SELECT ud.id, ud.name, ud.gender, ud.email, "
                        + "ua.date, ua.checkin, ua.checkout "
                        + "FROM userdetails ud "
                        + "LEFT JOIN userattendance ua ON ud.id = ua.userid "
                        + "WHERE ud.id = " + searchId;

                ResultSet rs = st.executeQuery(sqlQuery);

                Map<LocalDate, String[]> attendanceMap = new HashMap<>();
                String name = "", gender = "", email = "";

                boolean found = false;

                while (rs.next()) {
                    found = true;

                    name = rs.getString("name");
                    gender = rs.getString("gender");
                    email = rs.getString("email");

                    if (rs.getString("date") != null) {
                        LocalDate date = LocalDate.parse(rs.getString("date"));
                        String checkIn = rs.getString("checkin");
                        String checkOut = rs.getString("checkout");

                        attendanceMap.put(date, new String[]{checkIn, checkOut});
                    }
                }

                if (!found) {
                    JOptionPane.showMessageDialog(null, "Student Not Found");
                    return;
                }

                int presentCount = 0;
                int absentCount = 0;

                LocalDate currentDate = fromDate;

                while (!currentDate.isAfter(toDate)) {

                    String[] record = attendanceMap.get(currentDate);

                    String checkIn = null;
                    String checkOut = null;

                    if (record != null) {
                        checkIn = record[0];
                        checkOut = record[1];
                    }

                    String status;

                    if (checkIn != null && checkOut != null) {
                        status = "Present";
                        presentCount++;
                    } else {
                        status = "Absent";
                        absentCount++;
                    }

                    model.addRow(new Object[]{
                        searchId, name, gender, email,
                        currentDate.toString(),
                        checkIn == null ? "-" : checkIn,
                        checkOut == null ? "-" : checkOut,
                        status
                    });

                    currentDate = currentDate.plusDays(1);
                }

                lblPresent.setText(String.valueOf(presentCount));
                lblAbsent.setText(String.valueOf(absentCount));

                return;
            }

            // 🔥 NORMAL CASE
            String sqlQuery;

            if (fromDate != null && toDate != null) {
                sqlQuery = "SELECT ud.id, ud.name, ud.gender, ud.email, "
                        + "ua.date, ua.checkin, ua.checkout "
                        + "FROM userdetails ud "
                        + "LEFT JOIN userattendance ua ON ud.id = ua.userid "
                        + "AND ua.date BETWEEN '" + fromDate + "' AND '" + toDate + "' ";
            } else if (fromDate != null) {
                sqlQuery = "SELECT ud.id, ud.name, ud.gender, ud.email, "
                        + "ua.date, ua.checkin, ua.checkout "
                        + "FROM userdetails ud "
                        + "LEFT JOIN userattendance ua ON ud.id = ua.userid "
                        + "AND ua.date = '" + fromDate + "' ";
            } else {
                sqlQuery = "SELECT ud.id, ud.name, ud.gender, ud.email, "
                        + "ua.date, ua.checkin, ua.checkout "
                        + "FROM userdetails ud "
                        + "LEFT JOIN userattendance ua ON ud.id = ua.userid ";
            }

            if (searchId != null) {
                sqlQuery += "WHERE ud.id = " + searchId;
            }

            ResultSet rs = st.executeQuery(sqlQuery);

            int presentCount = 0;
            int absentCount = 0;
            boolean found = false;

            while (rs.next()) {
                found = true;

                String checkIn = rs.getString("checkin");
                String checkOut = rs.getString("checkout");

                String status;

                if (checkIn != null && checkOut != null) {
                    status = "Present";
                    presentCount++;
                } else {
                    status = "Absent";
                    absentCount++;
                }

                model.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("name"),
                    rs.getString("gender"),
                    rs.getString("email"),
                    rs.getString("date") == null ? "-" : rs.getString("date"),
                    checkIn == null ? "-" : checkIn,
                    checkOut == null ? "-" : checkOut,
                    status
                });
            }

            if (!found && searchId != null) {
                JOptionPane.showMessageDialog(null, "Student Not Found");
            }

            lblPresent.setText(String.valueOf(presentCount));
            lblAbsent.setText(String.valueOf(absentCount));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }

    private Long countWeekdays(LocalDate start, LocalDate end) {
        long count = 0;
        LocalDate date = start;
        while (date.isBefore(end) || date.equals(end)) {
            if (!(date.getDayOfWeek() == DayOfWeek.SATURDAY || date.getDayOfWeek() == DayOfWeek.SUNDAY)) {
                count++;
            }
            date = date.plusDays(1);
        }
        return count;
    }
}
